channel_map = {
    0: {"id": 0, "alias": "ZK", "label": "Kesselstatus", "mqtt_name": "Kesselstatus", "unit": ""},
    1: {"id": 1, "alias": "O2", "label": "O2-Gehalt", "mqtt_name": "o2", "unit": "%"},
    2: {"id": 2, "alias": "O2soll", "label": "O2-Sollwert", "mqtt_name": "o2soll", "unit": "%"},
    3: {"id": 3, "alias": "TK", "label": "Kesseltemperatur", "mqtt_name": "Kesseltemperatur", "unit": "°C"},
    4: {"id": 4, "alias": "TKsoll", "label": "Kessel-Solltemperatur", "mqtt_name": "tksoll", "unit": "°C"},
    5: {"id": 5, "alias": "TRL", "label": "Rücklauftemperatur", "mqtt_name": "trl", "unit": "°C"},
    6: {"id": 6, "alias": "TRLsoll", "label": "Rücklauf-Solltemperatur", "mqtt_name": "trlsoll", "unit": "°C"},
    7: {"id": 7, "alias": "Spreizung", "label": "Temperaturspreizung", "mqtt_name": "spreizung", "unit": "°C"},
    8: {"id": 8, "alias": "TRG", "label": "Rauchgastemperatur", "mqtt_name": "Rauchgastemperatur", "unit": "°C"},
    9: {"id": 9, "alias": "SZist", "label": "Saugzug Ist", "mqtt_name": "szist", "unit": "%"},
    10: {"id": 10, "alias": "SZsoll", "label": "Saugzug Soll", "mqtt_name": "szsoll", "unit": "%"},
    11: {"id": 11, "alias": "TPo", "label": "Puffer Oben", "mqtt_name": "temperatur_puffer_oben", "unit": "°C"},
    12: {"id": 12, "alias": "Temperatur_Puffer_Mitte", "label": "Puffer Mitte", "mqtt_name": "temperatur_puffer_mitte", "unit": "°C"},
    13: {"id": 13, "alias": "Temperatur_Puffer_Unten", "label": "Puffer Unten", "mqtt_name": "temperatur_puffer_unten", "unit": "°C"},
    14: {"id": 14, "alias": "Puff_Fuellgrad", "label": "Pufferfüllgrad", "mqtt_name": "puff_fuellgrad", "unit": "%"},
    15: {"id": 15, "alias": "Puffer_soll_oben", "label": "Puffer Sollwert Oben", "mqtt_name": "puffer_soll_oben", "unit": "°C"},
    16: {"id": 16, "alias": "Puffer_soll_unten", "label": "Puffer Sollwert Unten", "mqtt_name": "puffer_soll_unten", "unit": "°C"},
    17: {"id": 17, "alias": "PuffZustand", "label": "Pufferzustand", "mqtt_name": "puffzustand", "unit": ""},
    18: {"id": 18, "alias": "Max_Anf_Kessel", "label": "Max Kesselanforderung", "mqtt_name": "max_anf_kessel", "unit": ""},
    19: {"id": 19, "alias": "TFW", "label": "Frischwassertemperatur", "mqtt_name": "tfw", "unit": "°C"},
    20: {"id": 20, "alias": "Leistung", "label": "Ausgangsleistung", "mqtt_name": "leistung", "unit": "%"},
    21: {"id": 21, "alias": "ESsoll", "label": "Einschubschnecke Soll", "mqtt_name": "essoll", "unit": "%"},
    22: {"id": 22, "alias": "minLeistTRG", "label": "Min Leistung Rauchgas", "mqtt_name": "minleisttrg", "unit": "%"},
    23: {"id": 23, "alias": "maxLeistTRG", "label": "Max Leistung Rauchgas", "mqtt_name": "maxleisttrg", "unit": "%"},
    24: {"id": 24, "alias": "maxLeistFuell", "label": "Max Leistung Füllung", "mqtt_name": "maxleistfuell", "unit": "%"},
    25: {"id": 25, "alias": "maxLeistTPO", "label": "Max Leistung Puffer Oben", "mqtt_name": "maxleisttpo", "unit": "%"},
    26: {"id": 26, "alias": "ESRegler", "label": "Einschubschnecken-Regler", "mqtt_name": "esregler", "unit": "%"},
    27: {"id": 27, "alias": "Regler_K", "label": "Regler K", "mqtt_name": "regler_k", "unit": ""},
    28: {"id": 28, "alias": "KeBrstScale", "label": "Kessel-Brenner-Skalierung", "mqtt_name": "kebrstscale", "unit": "%"},
    29: {"id": 29, "alias": "Programm", "label": "Programm", "mqtt_name": "programm", "unit": ""},
    30: {"id": 30, "alias": "Stoerungs_Nr", "label": "Störungsnummer", "mqtt_name": "stoerungs_nr", "unit": ""},
    31: {"id": 31, "alias": "Max_Anf_ZenPuf", "label": "Max Zentralpuffer-Anforderung", "mqtt_name": "max_anf_zenpuf", "unit": "°C"},
    32: {"id": 32, "alias": "I_Es", "label": "Strom Einschubschnecke", "mqtt_name": "i_es", "unit": "mA"},
    33: {"id": 33, "alias": "I_Ra", "label": "Strom Rost", "mqtt_name": "i_ra", "unit": "mA"},
    34: {"id": 34, "alias": "I_Aa", "label": "Strom Aschenschnecke", "mqtt_name": "i_aa", "unit": "mA"},
    35: {"id": 35, "alias": "I_Sr", "label": "Strom Schürer", "mqtt_name": "i_sr", "unit": "mA"},
    36: {"id": 36, "alias": "I_Rein", "label": "Strom Reinigung", "mqtt_name": "i_rein", "unit": "mA"},
    37: {"id": 37, "alias": "BLDC_ES_ist", "label": "BLDC Einschubschnecke Ist", "mqtt_name": "bldc_es_ist", "unit": "rpm"},
    38: {"id": 38, "alias": "BLDC_ES_soll", "label": "BLDC Einschubschnecke Soll", "mqtt_name": "bldc_es_soll", "unit": "rpm"},
    39: {"id": 39, "alias": "LZ_ES_seit_Fuell", "label": "Laufzeit seit Füllung", "mqtt_name": "lz_es_seit_fuell", "unit": "Min"},
    40: {"id": 40, "alias": "LZ_ES_seit_Ent", "label": "Laufzeit seit Entaschung", "mqtt_name": "lz_es_seit_ent", "unit": "Min"},
    41: {"id": 41, "alias": "Anzahl_Entasch", "label": "Anzahl Entaschungen", "mqtt_name": "anzahl_entasch", "unit": ""},
    42: {"id": 42, "alias": "Anzahl_SR_Beweg", "label": "Anzahl Schürerbewegungen", "mqtt_name": "anzahl_sr_beweg", "unit": ""},
    43: {"id": 43, "alias": "Lagerstand", "label": "Pelletvorrat", "mqtt_name": "lagerstand", "unit": "kg"},
    44: {"id": 44, "alias": "Pelletverbrauch", "label": "Pelletverbrauch", "mqtt_name": "pelletverbrauch", "unit": "kg"},
    45: {"id": 45, "alias": "Heiz_P_Lambda", "label": "Lambda Heizleistung", "mqtt_name": "heiz_p_lambda", "unit": "W"},
    46: {"id": 46, "alias": "Heiz_U_Lambda", "label": "Lambda Heizspannung", "mqtt_name": "heiz_u_lambda", "unit": "V"},
    47: {"id": 47, "alias": "Heiz_I_Lambda", "label": "Lambda Heizstrom", "mqtt_name": "heiz_i_lambda", "unit": "mA"},
    48: {"id": 48, "alias": "U_Lambda", "label": "Lambda Spannung", "mqtt_name": "u_lambda", "unit": "mV"},
    49: {"id": 49, "alias": "U_Netzteil", "label": "Netzteil-Spannung", "mqtt_name": "u_netzteil", "unit": "mV"},
    50: {"id": 50, "alias": "T_Spuelung", "label": "Spültemperatur", "mqtt_name": "t_spuelung", "unit": "°C"},
    51: {"id": 51, "alias": "BRT", "label": "Brennraumtemperatur", "mqtt_name": "brt", "unit": "°C"},
    52: {"id": 52, "alias": "Tplat", "label": "Platinentemperatur", "mqtt_name": "tplat", "unit": "°C"},
    53: {"id": 53, "alias": "TVG", "label": "Vorlauftemperatur Gesamt", "mqtt_name": "tvg", "unit": "°C"},
    54: {"id": 54, "alias": "TVG2", "label": "Vorlauftemperatur 2", "mqtt_name": "tvg2", "unit": "°C"},
    55: {"id": 55, "alias": "AIN17", "label": "Analogeingang 17", "mqtt_name": "ain17", "unit": "V"},
    56: {"id": 56, "alias": "Aussentemperatur", "label": "Außentemperatur", "mqtt_name": "aussentemperatur", "unit": "°C"},
    57: {"id": 57, "alias": "TA_Gem", "label": "Außentemperatur Gemittelt", "mqtt_name": "ta_gem", "unit": "°C"},
    58: {"id": 58, "alias": "Effizienz", "label": "Wirkungsgrad", "mqtt_name": "effizienz", "unit": "%"},
    59: {"id": 59, "alias": "Programm_HKM1", "label": "Programm HK Modul 1", "mqtt_name": "programm_hkm1", "unit": ""},
    60: {"id": 60, "alias": "ExtHK_Solltmp", "label": "Ext. Heizkreis Solltemperatur", "mqtt_name": "exthk_solltmp", "unit": "°C"},
    61: {"id": 61, "alias": "ExtHK_2_Solltmp", "label": "Ext. Heizkreis 2 Solltemperatur", "mqtt_name": "exthk_2_solltmp", "unit": "°C"},
    62: {"id": 62, "alias": "TVL_A", "label": "Vorlauf HK A", "mqtt_name": "tvl_a", "unit": "°C"},
    63: {"id": 63, "alias": "TVLs_A", "label": "Vorlauf Soll HK A", "mqtt_name": "tvls_a", "unit": "°C"},
    64: {"id": 64, "alias": "TRA_A", "label": "Rücklauf HK A", "mqtt_name": "tra_a", "unit": "°C"},
    65: {"id": 65, "alias": "TRs_A", "label": "Rücklauf Soll HK A", "mqtt_name": "trs_a", "unit": "°C"},
    66: {"id": 66, "alias": "HKZustand_A", "label": "Zustand HK A", "mqtt_name": "hkzustand_a", "unit": ""},
    67: {"id": 67, "alias": "FRA_Zustand", "label": "Raumthermostat A Zustand", "mqtt_name": "fra_zustand", "unit": ""},
    68: {"id": 68, "alias": "HKPA_Status", "label": "Heizkreispumpe A Status", "mqtt_name": "hkpa_status", "unit": ""},
    69: {"id": 69, "alias": "TVL_1", "label": "Vorlauf HK 1", "mqtt_name": "tvl_1", "unit": "°C"},
    70: {"id": 70, "alias": "TVLs_1", "label": "Vorlauf Soll HK 1", "mqtt_name": "tvls_1", "unit": "°C"},
    71: {"id": 71, "alias": "TRA_1", "label": "Rücklauf HK 1", "mqtt_name": "tra_1", "unit": "°C"},
    72: {"id": 72, "alias": "TRs_1", "label": "Rücklauf Soll HK 1", "mqtt_name": "trs_1", "unit": "°C"},
    73: {"id": 73, "alias": "HKZustand_1", "label": "Zustand HK 1", "mqtt_name": "hkzustand_1", "unit": ""},
    74: {"id": 74, "alias": "FR1_Zustand", "label": "Raumthermostat 1 Zustand", "mqtt_name": "fr1_zustand", "unit": ""},
    75: {"id": 75, "alias": "HKP1_Status", "label": "Heizkreispumpe 1 Status", "mqtt_name": "hkp1_status", "unit": ""},
    76: {"id": 76, "alias": "TVL_2", "label": "Vorlauf HK 2", "mqtt_name": "tvl_2", "unit": "°C"},
    77: {"id": 77, "alias": "TVLs_2", "label": "Vorlauf Soll HK 2", "mqtt_name": "tvls_2", "unit": "°C"},
    78: {"id": 78, "alias": "TRA_2", "label": "Rücklauf HK 2", "mqtt_name": "tra_2", "unit": "°C"},
    79: {"id": 79, "alias": "TRs_2", "label": "Rücklauf Soll HK 2", "mqtt_name": "trs_2", "unit": "°C"},
    80: {"id": 80, "alias": "HKZustand_2", "label": "Zustand HK 2", "mqtt_name": "hkzustand_2", "unit": ""},
    81: {"id": 81, "alias": "FR2_Zustand", "label": "Raumthermostat 2 Zustand", "mqtt_name": "fr2_zustand", "unit": ""},
    82: {"id": 82, "alias": "HKP2_Status", "label": "Heizkreispumpe 2 Status", "mqtt_name": "hkp2_status", "unit": ""},
    83: {"id": 83, "alias": "TVL_3", "label": "Vorlauf HK 3", "mqtt_name": "tvl_3", "unit": "°C"},
    84: {"id": 84, "alias": "TVLs_3", "label": "Vorlauf Soll HK 3", "mqtt_name": "tvls_3", "unit": "°C"},
    85: {"id": 85, "alias": "TRA_3", "label": "Rücklauf HK 3", "mqtt_name": "tra_3", "unit": "°C"},
    86: {"id": 86, "alias": "TRs_3", "label": "Rücklauf Soll HK 3", "mqtt_name": "trs_3", "unit": "°C"},
    87: {"id": 87, "alias": "HKZustand_3", "label": "Zustand HK 3", "mqtt_name": "hkzustand_3", "unit": ""},
    88: {"id": 88, "alias": "FR3_Zustand", "label": "Raumthermostat 3 Zustand", "mqtt_name": "fr3_zustand", "unit": ""},
    89: {"id": 89, "alias": "HKP3_Status", "label": "Heizkreispumpe 3 Status", "mqtt_name": "hkp3_status", "unit": ""},
    90: {"id": 90, "alias": "TVL_4", "label": "Vorlauf HK 4", "mqtt_name": "tvl_4", "unit": "°C"},
    91: {"id": 91, "alias": "TVLs_4", "label": "Vorlauf Soll HK 4", "mqtt_name": "tvls_4", "unit": "°C"},
    92: {"id": 92, "alias": "TRA_4", "label": "Rücklauf HK 4", "mqtt_name": "tra_4", "unit": "°C"},
    93: {"id": 93, "alias": "TRs_4", "label": "Rücklauf Soll HK 4", "mqtt_name": "trs_4", "unit": "°C"},
    94: {"id": 94, "alias": "HKZustand_4", "label": "Zustand HK 4", "mqtt_name": "hkzustand_4", "unit": ""},
    95: {"id": 95, "alias": "FR4_Zustand", "label": "Raumthermostat 4 Zustand", "mqtt_name": "fr4_zustand", "unit": ""},
    96: {"id": 96, "alias": "HKP4_Status", "label": "Heizkreispumpe 4 Status", "mqtt_name": "hkp4_status", "unit": ""},
    97: {"id": 97, "alias": "TVL_B", "label": "Vorlauf HK B", "mqtt_name": "tvl_b", "unit": "°C"},
    98: {"id": 98, "alias": "TVLs_B", "label": "Vorlauf Soll HK B", "mqtt_name": "tvls_b", "unit": "°C"},
    99: {"id": 99, "alias": "TRA_B", "label": "Rücklauf HK B", "mqtt_name": "tra_b", "unit": "°C"},
    100: {"id": 100, "alias": "TRs_B", "label": "Rücklauf Soll HK B", "mqtt_name": "trs_b", "unit": "°C"},
    101: {"id": 101, "alias": "HKZustand_B", "label": "Zustand HK B", "mqtt_name": "hkzustand_b", "unit": ""},
    102: {"id": 102, "alias": "FRB_Zustand", "label": "Raumthermostat B Zustand", "mqtt_name": "frb_zustand", "unit": ""},
    103: {"id": 103, "alias": "HKPB_Status", "label": "Heizkreispumpe B Status", "mqtt_name": "hkpb_status", "unit": ""},
    104: {"id": 104, "alias": "TBA", "label": "Warmwasser A", "mqtt_name": "tba", "unit": "°C"},
    105: {"id": 105, "alias": "TBs_A", "label": "Warmwasser Soll A", "mqtt_name": "tbs_a", "unit": "°C"},
    106: {"id": 106, "alias": "TB1", "label": "Warmwasser 1", "mqtt_name": "tb1", "unit": "°C"},
    107: {"id": 107, "alias": "Boiler", "label": "Boiler", "mqtt_name": "boiler", "unit": "°C"},
    108: {"id": 108, "alias": "BoiZustand_1", "label": "Boilerzustand 1", "mqtt_name": "boizustand_1", "unit": ""},
    109: {"id": 109, "alias": "TB2", "label": "Warmwasser 2", "mqtt_name": "tb2", "unit": "°C"},
    110: {"id": 110, "alias": "TBs_2", "label": "Warmwasser Soll 2", "mqtt_name": "tbs_2", "unit": "°C"},
    111: {"id": 111, "alias": "BoiZustand_2", "label": "Boilerzustand 2", "mqtt_name": "boizustand_2", "unit": ""},
    112: {"id": 112, "alias": "TBB", "label": "Warmwasser B", "mqtt_name": "tbb", "unit": "°C"},
    113: {"id": 113, "alias": "TBs_B", "label": "Warmwasser Soll B", "mqtt_name": "tbs_b", "unit": "°C"},
    114: {"id": 114, "alias": "HKR_Anf", "label": "Heizkreis-Anforderung", "mqtt_name": "hkr_anf", "unit": "°C"},
    115: {"id": 115, "alias": "Anf_HKR0", "label": "Anforderung HK 0", "mqtt_name": "anf_hkr0", "unit": "°C"},
    116: {"id": 116, "alias": "Anf_HKR1", "label": "Anforderung HK 1", "mqtt_name": "anf_hkr1", "unit": "°C"},
    117: {"id": 117, "alias": "Anf_HKR2", "label": "Anforderung HK 2", "mqtt_name": "anf_hkr2", "unit": "°C"},
    118: {"id": 118, "alias": "Anf_HKR3", "label": "Anforderung HK 3", "mqtt_name": "anf_hkr3", "unit": "°C"},
    119: {"id": 119, "alias": "Anf_HKR4", "label": "Anforderung HK 4", "mqtt_name": "anf_hkr4", "unit": "°C"},
    120: {"id": 120, "alias": "Anf_HKR5", "label": "Anforderung HK 5", "mqtt_name": "anf_hkr5", "unit": "°C"},
    121: {"id": 121, "alias": "Anf_HKR6", "label": "Anforderung HK 6", "mqtt_name": "anf_hkr6", "unit": "°C"},
    122: {"id": 122, "alias": "Anf_HKR7", "label": "Anforderung HK 7", "mqtt_name": "anf_hkr7", "unit": "°C"},
    123: {"id": 123, "alias": "Anf_HKR8", "label": "Anforderung HK 8", "mqtt_name": "anf_hkr8", "unit": "°C"},
    124: {"id": 124, "alias": "Anf_HKR9", "label": "Anforderung HK 9", "mqtt_name": "anf_hkr9", "unit": "°C"},
    125: {"id": 125, "alias": "Anf_HKR10", "label": "Anforderung HK 10", "mqtt_name": "anf_hkr10", "unit": "°C"},
    126: {"id": 126, "alias": "Anf_HKR11", "label": "Anforderung HK 11", "mqtt_name": "anf_hkr11", "unit": "°C"},
    127: {"id": 127, "alias": "Anf_HKR12", "label": "Anforderung HK 12", "mqtt_name": "anf_hkr12", "unit": "°C"},
    128: {"id": 128, "alias": "Anf_HKR13", "label": "Anforderung HK 13", "mqtt_name": "anf_hkr13", "unit": "°C"},
    129: {"id": 129, "alias": "Anf_HKR14", "label": "Anforderung HK 14", "mqtt_name": "anf_hkr14", "unit": "°C"},
    130: {"id": 130, "alias": "Anf_HKR15", "label": "Anforderung HK 15", "mqtt_name": "anf_hkr15", "unit": "°C"},
    131: {"id": 131, "alias": "UsePos", "label": "Positionsnutzung", "mqtt_name": "usepos", "unit": ""},
    132: {"id": 132, "alias": "AUPSoll", "label": "AUPSoll", "mqtt_name": "aupsoll", "unit": "mm"},
    133: {"id": 133, "alias": "AUPIst", "label": "AUPIst", "mqtt_name": "aupist", "unit": "mm"},
    134: {"id": 134, "alias": "AUPStrom", "label": "AUPStrom", "mqtt_name": "aupstrom", "unit": "mA"},
    135: {"id": 135, "alias": "TPO_ZusPuf1", "label": "TPO_ZusPuf1", "mqtt_name": "tpo_zuspuf1", "unit": "°C"},
    136: {"id": 136, "alias": "TPM_ZusPuf1", "label": "TPM_ZusPuf1", "mqtt_name": "tpm_zuspuf1", "unit": "°C"},
    137: {"id": 137, "alias": "TPU_ZusPuf1", "label": "TPU_ZusPuf1", "mqtt_name": "tpu_zuspuf1", "unit": "°C"},
    138: {"id": 138, "alias": "Wasserdruck", "label": "Wasserdruck", "mqtt_name": "wasserdruck", "unit": "bar"},
}

